### ISSUE TITLE
Digest errors on page refresh with 3rd party libraries

### ISSUE THREAD

**Issue by adamlubek** [ui-router/angular-hybrid#103]
Hi,
I have a problem with angular-hybrid when I'm trying to use it with angular-redux. Problem is digest error when trying to dispatch an redux action on component init when refreshing lazy loaded module. 

Here's your sample app forked with changes to replicate the problem: 
https://github.com/adamlubek/sample-app-angular-hybrid/tree/angular-cli-with-angular-redux
commit with changes: https://github.com/adamlubek/sample-app-angular-hybrid/commit/510ab00fd3ed99898ff03ab66d6dbafd16bfdc53

To see the error, log into the app, go to contacts page and refresh the page, you should see digest error in console. It happens most of the time but if it doesn't refresh few times and you should get it. 

![digesterror](https://user-images.githubusercontent.com/8349742/37219017-1d69e710-23ba-11e8-87fb-12471af9a177.png)

```
angular.js:14800 Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.6.9/$rootScope/inprog?p0=%24digest
    at eval (angular.js:116)
    at beginPhase (angular.js:18906)
    at Scope.$digest (angular.js:18328)
    at eval (static.js:1511)
    at SafeSubscriber.schedulerFn [as _next] (core.js:4343)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:240)
    at SafeSubscriber.next (Subscriber.js:187)
    at Subscriber._next (Subscriber.js:128)
    at Subscriber.next (Subscriber.js:92)
    at EventEmitter.Subject.next (Subject.js:56)
```

I'm wondering if you could look into feasibility of fixing it please

**Comment by adamlubek** [comment]
Digest error on refresh also happens with other 3rd party libraries. See this commit:
https://github.com/adamlubek/sample-app-angular-hybrid/commit/917ae3a65a6384013cf6c8ad7d85b1b9114f3d31

It contains example of adding devextreme library and just adding library's component on lazy loaded component will cause digest error as described above (see `<dx-data-grid></dx-data-grid>` - https://github.com/adamlubek/sample-app-angular-hybrid/commit/917ae3a65a6384013cf6c8ad7d85b1b9114f3d31#diff-399c6b691d77d7666666e1610ee40c25R6)

**Comment by adamlubek** [comment]
Can library creator/maintainer look into this problem please? We've got enterprise app with multiple feature packages that need to be lazy loaded, otherwise app startup time is unacceptable. UI-Router served us well but now it feels like this is becoming a non maintained legacy project...

**Comment by adamlubek** [comment]
If PR on uirouter/core is accepted (thus bumping uirouter/core to 5.0.18), can we have it installed in uirouter/angular-hybrid version 3.x? (i.e. thus bumping uirouter/angular-hybrid to 3.1.11)

**Comment by christopherthielen** [comment]
@adamlubek Shortly after closing your PR, I experimented with running the ui-router bootstrap inside the Angular zone. It seems to have solved the problem.  

When bootstrapping ui-router, explicitly run the `listen()` and `sync()` in angular zone.  I had assumed that the `bootstrapModule(...).then()` would be run in that zone, but it doesn't seem to be the case.

```ts
// Manually bootstrap the Angular app
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  // Intialize the Angular Module
  // get() the UIRouter instance from DI to initialize the router
  const urlService: UrlService = platformRef.injector.get(UIRouter).urlService;

  const startRouter = () => {
    // Instruct UIRouter to listen to URL changes
    urlService.listen();
    urlService.sync();
  };

  platformRef.injector.get<NgZone>(NgZone).run(startRouter);
});
```

Can you try this out and let me know if this solves your problems?  It works in the sample app reproduction repo you provided.  I'm going to also update the README.

Sorry for the long delay in my response.

**Comment by adamlubek** [comment]
thanks @christopherthielen , we'll check your solution against our setup and get back to you :)

**Comment by jimmylin212** [comment]
Is this solution also work with Angular 7.1.0? I encounter the same problem using Angular 7.1.0 with `@uirouter/angular-hybrid` version 6.0.2.

**Comment by christopherthielen** [comment]
@jimmylin212 did the solution work with angular 6 but stop working when you switched to angular 7?
