### ISSUE TITLE
zone.js seems to be going crazy

### ISSUE THREAD

**Issue by httpete** [ui-router/angular-hybrid#135]
I am seeing bad performance slowdowns which grind the browser up.. 

https://github.com/angular/zone.js/issues/1020

have you seen this Chris in a hybrid app?

**Comment by httpete** [comment]
Hi @christopherthielen  I see that 15 days ago you changed the way you bootstrap to do it in a zone.. I just changed my app to this and it seems to help a ton - can you just confirm that is why you changed the bootstrapping approach? Thank you.

**Comment by christopherthielen** [comment]
The commit in question: https://github.com/ui-router/angular-hybrid/commit/9df20f0f29e81897cb7695b540dd059cf4ebfdee

No, that change was not specifically to fix performance issues.  Rather, it was changed to avoid infinite digests as reported in https://github.com/ui-router/angular-hybrid/issues/103.     However, I can see how this change might also fix some zone based perf issues!

**Comment by httpete** [comment]
It's tremendously better now! The browser would just eat all processor and cause the entire machine to stall I think that angular.js' chatty digest and all the event listeners just drove it bonkers. The new file layout you have now is much easier to understand as well.
