### ISSUE TITLE
ui-view bindings aren't propagating to angular child state component

### ISSUE THREAD

**Issue by mikelseverson** [ui-router/angular-hybrid#159]
Using https://ui-router.github.io/guide/ng1/route-to-component#routed-parentchild-component-communication
I'm attempting to pass bindings down VIA a `<ui-view> `

```
<div
   ui-view
   data="$ctrl.data"
   callback="$ctrl.callback($event)">
</div>
```

Children states with angularJS components are working great.
Children states with angular components are not receiving the bindings.

It seems ui-view-ng-upgrade is not propagating the bindings down.
Is this supported at this time?
Or do you any ideas to achieve similar functionality?

Thanks!

**Comment by mikelseverson** [comment]
My mistake, at this time this is not supported.
In the case of getting data to routed components, I'll look into using resolved instead for now.

Looks like this functionality is under discussion here: https://github.com/ui-router/angular/issues/138

**Comment by christopherthielen** [comment]
This is not supported for Angular components.  It's not even supported by regular (non-hybrid) `@uirouter/angular`.  There isn't an easy way to dynamically bind to arbitrary inputs of angular components.  The angular compiler needs to know up front what is being bound.
