### ISSUE TITLE
Getting params as undefined when navigated to nested route.

### ISSUE THREAD

**Issue by sandeepb6** [ui-router/angular-hybrid#161]
Hi,

When i'm clicking on nested route link, getting params undefined error. But when i do ctrl+click it is opening in new tab perfectly. 
Link will be like below:
`<a ui-sref=".child1" href="#hello/1/item1">Click here</a>.`

In the above href will be binded in run time. I'm facing this issue after upgrading ui router. Please help me to fix this.

FYI i'm using  **uirouter/angular-hybrid**: "4.0.0"

**Comment by christopherthielen** [comment]
Can you show me how to reproduce the error?   Here's a starter with relative nested links: https://stackblitz.com/edit/ui-router-angular-hybrid-issue161?file=angularjs.module.ts
