### ISSUE TITLE
angular-ui-router 0.2.x => ui-router-upgrade: routing works but ui-view not rendering

### ISSUE THREAD

**Issue by AndrewPa** [ui-router/angular-hybrid#178]
I have a legacy application (AngularJS 1.5.x) using angular-ui-router 0.2.x and all of the routes are set up using the legacy syntax in config blocks. Here's an example:

```
angular
    .module('myModule', [ 'ui.router.upgrade' ])
    .config(function($stateProvider) {
        $stateProvider
            .state('my-component', {
                titleKey: 'Welcome to My Component',
                url: '/myComponent',
                template: '<my-component></my-component>',
                resolve: {
                    function() { return isAuthenticated(); }
                }
                params: {
                    redirect: null,
                    message: null
                }
            });
    });
```
Ultimately I'm attempting to wrap this application in an Angular 6 wrapper using `ngUpgrade`. The basic bootstrapping appears to be working and some page elements outside of the `ui-view` are being rendered.

I added breakpoints in the body of `isAuthenticated` and the promise is generated and resolved as expected. The `$state.go` method also works in other components, and I can see the URL change as expected.

The only issue is that the `ui-view` component is empty instead of containing the template. Even when I change the template to something static like `<div>Hello World</div>` I don't see anything in the inspector inside of the `<div ui-view></div>`, which we put on the `index.html`.

**Comment by xfh** [comment]
I had the same issue with an existing hybrid app (AngularJS 1.6, Angular 5), after upgrading to Angular 6.

Before the upgrade I was using a custom Webpack 3 build. Since Angular 6 requires Webpack 4 I decided to give the angular cli a shot: I uninstalled all my Webpack plugins and upgraded Webpack and the dev-server to the latest versions. From then on my ui-views started rendering again with `ng serve`. How are you building your application?

**Comment by AndrewPa** [comment]
@xfh Ultimately what I did was I had to keep the webpack setup I had, but made it more like the hidden configuration that Angular-CLI uses.

For styles and templates, you need to use `angular-template-loader` and add it to your TS loader:

```
 module: {
        rules: [{
                test: /\.(js|ts)$/,
                loader: [ 'ts-loader', 'angular2-template-loader' ],
                exclude: /node_modules/
            },
            // ...etc
}
```

Also for styles to compile properly you need to add to your rule for your less/sass loader to use `to-string-loader` instead of `style-loader`:

```
{
    test: /\.scss$/,
    loaders: ['to-string-loader', 'css-loader', 'sass-loader']
}
```
