### ISSUE TITLE
@angular/router module is required

### ISSUE THREAD

**Issue by pshurygin** [ui-router/angular-hybrid#184]
I'm not sure if this is intended or not, but i cannot use angular-hybrid router without installing @angular/router as a dependancy. This results in a pretty large footprint of the router. (ui-router core + ui-router angular + ui-router angularjs + @angular/router). Here is a visualization:
![image](https://user-images.githubusercontent.com/25816676/43898936-1a35ae56-9be9-11e8-8c36-4dd0053873d0.png)

And if I remove @angular/router from dependancy list, i get the following error on build(AOT):

> ERROR in @uirouter\angular\lib\uiRouterNgModule.ts(67,16): Error during template compile of 'makeChildProviders'
>   Could not resolve @angular/router relative to D:/Solomoto/impl/solo/SolomotoWebRole/node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts..

**Comment by chce** [comment]
I randomly found this comment by the ui-router developers while reading an issue on Angular's issue tracker:
https://github.com/angular/angular-cli/issues/4541#issuecomment-296505536

**Comment by pshurygin** [comment]
Thanks, so that means it's angular devs to blame for that. And there is no progress on that issue whatsoever for already 1.5 years, so I guess we are just supposed to live with that extra 20kb of useless code for our clients.

**Comment by chce** [comment]
There is a bit of progress on a related issue, but it doesn't really seem like top priority: https://github.com/angular/angular-cli/issues/9343
