### ISSUE TITLE
Support for ui.router.state.events?

### ISSUE THREAD

**Issue by jefim** [ui-router/angular-hybrid#185]
Hi, trying this out to migrate to Angular from AJS. Is there support at the moment for something like 'ui.router.state.events'? Or any workaround? Because after replacing uirouted with the angular-hybrid versions the state events module disappeared.

Any tips on how to temporarily work around this thing?

**Comment by AliceCasari** [comment]
Is possible?!?

**Comment by christopherthielen** [comment]
I know it's over 6 months late, but here's the answer:

Import the state events JS code then depend on `ui.router.state.events`

```js
import '@uirouter/angularjs/lib/legacy/stateEvents';
const app = angular.module('minimal', ['ui.router.upgrade', 'ui.router.state.events']);
```
