### ISSUE TITLE
Simple App with Ng1-to-ng2 Router

### ISSUE THREAD

**Issue by squadwuschel** [ui-router/angular-hybrid#21]
Could you please create a simple but complete app like the hybrid.zip sample with both routing versions in one app, that would be great, because the complex app is a bit too complex :-) for "normal" app developers like me :-)

**Comment by zourtney** [comment]
Agreed. I need a super-simple example that doesn't leverage `lazyLoad`. I attempted to work through it yesterday, but left utterly confused.

**Comment by schmitch** [comment]
I think it would be especially great to have a example that works well with angular-cli

**Comment by christopherthielen** [comment]
There is now a very simple example in https://github.com/ui-router/angular-hybrid/tree/master/example
