### ISSUE TITLE
Is it possible to use NG1 routes and Ng2 routes in one App?

### ISSUE THREAD

**Issue by squadwuschel** [ui-router/angular-hybrid#23]
I've tried to get it my old ng1 app working with ng1-to-ng2

I'am using ui router in my old Ng1 app with TypeScript and I've an route.config there and I'Ve created a component there.

          this.$stateProvider
                .state("HalloWelt",
                {
                    name: "HalloWelt",
                    url: "/HalloWelt",
                    component : App.Views.NgTest.HalloWeltComponent.module.name
                });

Then I've created a Ng2 app with ui router for Ng2 that routing within Ng2 works fine so far in an extra ngModule

    import { NgModule } from '@angular/core';
    import { CommonModule } from "@angular/common";
    import { BrowserModule } from '@angular/platform-browser';
    import { UIRouterModule, Ng2StateDeclaration } from "ui-router-ng2";
    
    import {} from "../../upgradeAdapter"
    import { LogSuche } from "./logsuche.component";
    import { Logsuchemenue } from "./logsuchemenue.component";
    import { Logmonitor } from "./logmonitor.component";
    
    let logMenue: Ng2StateDeclaration = { name: 'logviewer', url: "/logviewer", component: Logsuchemenue };
    let logSuche: Ng2StateDeclaration = { name: 'logviewer.logsuche', url: '/logsuche', component: LogSuche };
    let logMonitor: Ng2StateDeclaration = { name: 'logviewer.logmonitor', url: '/logmonitor', component: Logmonitor }
    
    
    @NgModule({
        imports: [ CommonModule, BrowserModule,
            UIRouterModule.forChild({ states: [logMenue, logSuche, logMonitor] }),
        ],
        declarations: [
            LogSuche,
            Logsuchemenue,
            Logmonitor
        ],
    })
    export class LogviewerModule {
        constructor() {
        }
    
    }

the upgrade adapter looks like this

    import { UpgradeAdapter } from '@angular/upgrade';
    import { forwardRef } from '@angular/core';
    import { AppModule } from "./app.modules";
    import { uiRouterNgUpgrade } from "ui-router-ng1-to-ng2";
    
    import {AppComponent} from "./Views/app.component";
    
    export const upgradeAdapter = new UpgradeAdapter(forwardRef(() => AppModule));
    upgradeAdapter.upgradeNg1Provider('$state');
    uiRouterNgUpgrade.setUpgradeAdapter(upgradeAdapter);
    
    upgradeAdapter.upgradeNg1Provider(App.Views.NgTest.HalloWeltComponent.module.name);
    
    App.Views.MainApp.ng1App.directive("app", <any>upgradeAdapter.downgradeNg2Component(AppComponent));

and my AppModule (root module)

    import { forwardRef, NgModule, NgModuleFactoryLoader, SystemJsNgModuleLoader, Inject } from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';
    import { UIRouterModule, UIRouter } from "ui-router-ng2";
    import { Ng1ToNg2Module } from "ui-router-ng1-to-ng2";
    
    import { AppComponent } from "./Views/app.component";
    import { LogviewerModule } from "./Views/LogViewer/_logviewer.modules";
    
    @NgModule({
        imports: [
            BrowserModule,
            Ng1ToNg2Module,
            LogviewerModule,
        ],
        declarations: [
            AppComponent
        ],
        providers: [
            { provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader }
        ]
    })
    export class AppModule {
    
        constructor( @Inject(UIRouter) router: UIRouter) {
           router.urlRouterProvider.otherwise('/logviewer/logsuche');
        }
    }

my application boot file 

    import { upgradeAdapter } from "./upgradeAdapter";
    upgradeAdapter.bootstrap(document.body, ['app.main', 'ui.router.upgrade']);

and my main Menue Navigation looks like this

      <li>
        <a uiSref="logviewer.logsuche" title="Logviewer">Logviewer</a>
     </li>
      <li>
          <a ui-sref="HalloWelt">Hallo Welt</a>
     </li>

the Navigation for "logviewer.logsuche" works fine which is defined in my Ng2 routing module but the "HalloWelt" is not working, its not detected because its not generating a link for this ui-sref. 
I am missing something or what I am doing wrong here? Is it even possible to use ng1 routings and ng2 routings in the same app or did I have to compare them in one place in ng1 or ng2?

**Comment by christopherthielen** [comment]
I realize this response is probably months too late for you.  However, we've released a new version 2.0.0 of this project as `@uirouter/angular-hybrid` which supports Angular 4.x etc.  The sample app is also updated and I think demonstrates how to create states in either ng1 or ng2 code.

https://github.com/ui-router/sample-app-ng1-to-ng2

One caveat I've run into in some apps is that the Angular portion doesn't actually get created because nothing depends on the Angular (2.x+) code.  If I remember correctly, I was able to trigger creation of the NgModule by explicitly getting something from the Angular Injector.

**Comment by christopherthielen** [comment]
We've released version 3.0 also

**Comment by christopherthielen** [comment]
> One caveat I've run into in some apps is that the Angular portion doesn't actually get created because nothing depends on the Angular (2.x+) code. If I remember correctly, I was able to trigger creation of the NgModule by explicitly getting something from the Angular Injector.

The pattern that solves this issue is to do `deferIntercept()` then `listen()` and `sync()` _after bootstrap is completed_.  This can be seen here: https://github.com/ui-router/sample-app-angular-hybrid/blob/ec6e41c11e1c226bed7912b53aa1fb88a51ca16a/app/bootstrap/bootstrap.ts#L75-L95

Closing because I believe the answers to these questions are demonstrated in the sample app.
