### ISSUE TITLE
Cannot provide mock `$state` in test cases.

### ISSUE THREAD

**Issue by tdecker91** [ui-router/angular-hybrid#234]
After using this library angular js tests that are providing mocks for  state service `$state` are no longer working. I've found that this is because the code is not receiving the mock `$state`. Instead the angular-hybrid `StateService` is being injected. 

I think this is because of how the injector is being changed to provide a merged ng1/ng2 injector. Is there a way to provide a mock `$state` in angularJS tests?

**Comment by christopherthielen** [comment]
I'm not sure I understand what's happening in your tests.  

Can I see an example?  How the injector is being accessed? I think the `mergedInjector` is only used inside resolves?

**Comment by tdecker91** [comment]
@christopherthielen 

Sorry, my original comment wasn't very clear.

I'm using karama test runner and using `$provide.value` to register my mock state with the injector.


Basic example of test
```javascript
import { mock } from 'angular';

describe('Controller test', function () {
  let provider;
  let $controller;
  let stateSpy;

  beforeEach(mock.module('appModule', function ($provide) {
    provider = $provide;
  }));

  beforeEach(inject(function (_$controller_) {
    $controller = _$controller_;
  }));

  beforeEach(function () {
    stateSpy = jasmine.createSpyObj('stateSpy', [
      'go'
    ]);

    provider.value('$state', stateSpy);
  });

  describe('create controller', function () {
    it('does something with mock state', function () {
      let controllerInstance = $controller('myController')

      // here controller should have been instantiated with mock state
      ...

    });
  });

});
```

Controller 
```javascript
class MyController {

  static $inject = [
    '$state'
  ];

  constructor($state: StateService) {
    // In test, constructor should be called with state spy
    ...
  }

}
```

After integrating the hybrid router, this setup no longer works. The angular js controllers in the test cases are being instantiated with hybrid router `StateService` and not my mocked state service.

For the meantime I have used the following work around.

```javascript
controller('myController', {
  $state: stateSpy
});
```

The issue with this is that the controller is instantiated with the hybrid router `StateService` and then `$state` is replaced with the mock. So anything in the constructor relying on the mock service will not work.
