### ISSUE TITLE
Angular7 is support or not? 

### ISSUE THREAD

**Issue by y8n** [ui-router/angular-hybrid#236]
Will ui-router/angular-hybrid support Angular7?

**Comment by scottnice** [comment]
Ditto

**Comment by rbnzdave** [comment]
doesnt seem like it

**Comment by icorne** [comment]
What seems to be your issues? I'm using it with angular 7

**Comment by david-meza** [comment]
It is working for me with Angular 7 as well. There's just a warning when running npm commands, but the library itself seems to be compatible.

`npm WARN @uirouter/angular-hybrid@6.0.2 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by rbnzdave** [comment]
I find I cant even install it, as there are requirements for angular6 from memory
latest PR to make it compatable with ng7 was denied from a few sources. havent re-looked in a while

**Comment by rbnzdave** [comment]
yeah there are still a bunch of open PR's mentioning getting it to support 7. This was what I was referring to.

**Comment by ngehlert** [comment]
angular 7 support for the core ui router just came by last week (https://github.com/ui-router/angular/issues/423)

@christopherthielen sorry to ping you in two different issues. can you please add support for angular 7 for the hybrid router. thanks in advance

**Comment by christopherthielen** [comment]
https://github.com/ui-router/angular-hybrid/releases/tag/7.0.0

**Comment by ngehlert** [comment]
awesome thanks
