### ISSUE TITLE
Can't set useHash to true in UIRouterUpgradeModule.forRoot

### ISSUE THREAD

**Issue by roypeled** [ui-router/angular-hybrid#237]
For some reason, we can't use the ```useHash``` property of UIRouterModule in UIRouterUpgradeModule.

The ```UIRouterModule.forRoot``` expect an interface of ```RootModule``` which supports ```useHash```, while ```UIRouterUpgradeModule.forRoot``` expects an interface of ```NgHybridStatesModule``` which extends ```StatesModule``` and does not support ```useHash```

**Comment by roypeled** [comment]
Temporary solution is to manually provide the location strategy to the app.
In your root module add the following:
```
import { LocationStrategy, HashLocationStrategy } from '@angular/common';

@NgModule({
	...,
	providers: [
		{
			provide: LocationStrategy,
			useClass: HashLocationStrategy,
		},
	],
})
```

**Comment by ghous92** [comment]
Hi @roypeled  , If the above solution helped , Can you please your the solution that will be very kind of you .
I am not able to do deep linking in Angular AngularJS Hybrid App using UI RouyerUpgradeModule
