### ISSUE TITLE
New UpgradeAdapter in Angular 2.2.3

### ISSUE THREAD

**Issue by trumbitta** [ui-router/angular-hybrid#24]
I can't find a way to make it work with the new way of using the UpgradeAdapter with Angular 2.2.3.

Ref: https://angular.io/docs/ts/latest/guide/upgrade.html

**Comment by jonrimmer** [comment]
I have hacked in support for upgrade/static into [my copy of ng1-to-ng2](https://github.com/jonrimmer/ng1-to-ng2). I also have a modified [copy of sample-app-ng1-to-ng2](https://github.com/jonrimmer/sample-app-ng1-to-ng2) that shows how to use it.

Hopefully this will be useful to any looking for a temporary workaround, at least. I could tidy it up into a pull request together if @christopherthielen thinks the approach looks sound?

**Comment by jonrimmer** [comment]
I have updated my hack a bit now I better understand how UpgradeModule works. You no longer need to call ```uiRouterNgUpgrade.setNg2Injector()```, as it's possible to get the ng2 injector from the ng1 injector (the static upgrader just changed the name its provided under).

**Comment by mischkl** [comment]
@christopherthielen is there any chance of using this patch (or the findings within it) to enable AOT support? (This is the last thing holding us back from integrating Angular 2 in our existing Angular 1 app.) ;)

**Comment by vladtar** [comment]
+1

**Comment by AymanNatsheh** [comment]
+1

**Comment by RaphyLi** [comment]
@jonrimmer do you try recently your fork? Because a try to implement them in my project, but when upgrade the `$uiRouter` the injector is undefined.

**Comment by jonrimmer** [comment]
@RaphyLi No, not for a while. There is a now an angular4 branch in this project. I would suggest trying that instead.

**Comment by RaphyLi** [comment]
@jonrimmer i will try. But I use Angular 2.4.10.

**Comment by christopherthielen** [comment]
Thanks @jonrimmer.
I've merged your changes into master and released it as `@uirouter/angular-upgrade` version 3.0.1
