### ISSUE TITLE
import 'angular' line should be removed

### ISSUE THREAD

**Issue by arslan2012** [ui-router/angular-hybrid#240]
As stated in [Angular-cli docs](https://github.com/angular/angular-cli/wiki/stories-global-scripts)
if AngularJS was added through scripts tag in angular-cli.json, then 
`import * as angular from 'angular';` shouldn't be used, or else angular will get call twice and get bundled twice even in production mode.

**Comment by wiltzius** [comment]
I was chasing down why we have 2 copies of angular in our builds now and traced it to this. We have our legacy Angular 1 application, which puts angular in global scope, and then we have our newer Angular 2 stuff using angular-hybrid.

How can we avoid having two copies of it?

**Comment by arslan2012** [comment]
i think angular-hybrid intents for user to use angular as a dynamic module. they didn't consider angular in global scope. I don't blame them tho, because detecting global then importing is kinda hard to do right now

**Comment by wiltzius** [comment]
I'm not sure what the intent was, but I do notice that in this repo the example uses angular as an 'external' in its webpack config:

https://github.com/ui-router/angular-hybrid/blob/master/example/webpack.config.js#L28

I had missed that earlier!

**Comment by arslan2012** [comment]
> I'm not sure what the intent was, but I do notice that in this repo the example uses angular as an 'external' in its webpack config:
> 
> https://github.com/ui-router/angular-hybrid/blob/master/example/webpack.config.js#L28
> 
> I had missed that earlier!

because this bug only appears in `ng build`

**Comment by christopherthielen** [comment]
Hopefully this is fixed in 7.0.0, please let me know if you have problems!
