### ISSUE TITLE
@angular/upgrade/static compatible

### ISSUE THREAD

**Issue by prasannapattam** [ui-router/angular-hybrid#26]
Is the hybrid setup compatible with the new upgrade module (@angular/upgrade/static). Please provide a sample or directions.

**Comment by christopherthielen** [comment]
I'm working on ng2 in the coming week or two.  Once I've released ui-router-ng2 `1.0.0-beta.4` I'll work on updating `ng1-to-ng2` codebase.

**Comment by trumbitta** [comment]
Duplicate of #24 ? :)

**Comment by mischkl** [comment]
Any news on this front?

**Comment by vladtar** [comment]
+1

**Comment by agent613** [comment]
Any update on this?  It doesn't seem possible to use AOT until this is resolved.

**Comment by RaphyLi** [comment]
@christopherthielen Any update on this?

**Comment by christopherthielen** [comment]
I think this should be ready soon.  I'm stealing [the work that @jonrimmer did](https://github.com/ui-router/angular-hybrid/issues/24#issuecomment-265029379) back in December.  (thanks Jon!)

**Comment by christopherthielen** [comment]
This is released as `@uirouter/angular-hybrid` version 3.0.1
