### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by ngehlert** [ui-router/angular-hybrid#296]
Would be great if you can add support for Angular 8

**Comment by SamanthaAdrichem** [comment]
Any known issues? Might be compatible already?

**Comment by ngehlert** [comment]
yeah can't compile due to wrong peer dependency.

as far as i can see it, it should be enough to just upgrade the version in the package.json. didn't find an issue with it while testing

**Comment by sorakthunly** [comment]
Can verify that the upgrade does not cause any issues so far. Please confirm the open PR

**Comment by ngehlert** [comment]
just wanna bump this since it is kind of important!

**Comment by christopherthielen** [comment]
released as `8.0.0`
