### ISSUE TITLE
ng1-to-ng2 compatibility with angular 2.4.x

### ISSUE THREAD

**Issue by sreekarun** [ui-router/angular-hybrid#30]
Angular version 2.4.7

While referencing the Ng1toNg2Module in the application module, the Angluar Cli gives an error as  ERROR in Ng1ToNg2Module is not an NgModule.

`import { Ng1ToNg2Module } from "ui-router-ng1-to-ng2";

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        Ng1ToNg2Module
    ],
    declarations: [
        AppComponent
    ],
    providers: [
        { provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader }
    ],
    bootstrap: [
        AppComponent
    ],
    entryComponents: [
        AppComponent
    ]
})
export class AppModule {

}
`

**Comment by sreekarun** [comment]
npm dependency warnings

npm WARN ui-router-ng1-to-ng2@1.0.15 requires a peer of @angular/core@~2.0.1 but none was installed.
npm WARN ui-router-ng1-to-ng2@1.0.15 requires a peer of @angular/upgrade@~2.0.1but none was installed.
npm WARN ui-router-ng1-to-ng2@1.0.15 requires a peer of rxjs@~5.0.0-beta.12 butnone was installed.
npm WARN ui-router-ng1-to-ng2@1.0.15 requires a peer of zone.js@~0.6.21 but none was installed.

Is 2.0.x a mandatory requirement ?

**Comment by mischkl** [comment]
+1

**Comment by j2d2** [comment]
+1

**Comment by shanshanzoe** [comment]
+1

**Comment by AymanNatsheh** [comment]
+1

**Comment by christopherthielen** [comment]
For angular 2.4 support, please use the last 1.x release of `ui-router-ng1-to-ng2` (version 1.0.15).

For angular 4 support, use `@uirouter/angular-hybrid` version 2.0.0 or higher.
