### ISSUE TITLE
Having trouble building my app using web pack. Please let me if i am missing any thing here.

### ISSUE THREAD

**Issue by chinra02** [ui-router/angular-hybrid#31]
ERROR in [at-loader] node_modules\angular-ui-router\lib\services.d.ts:15:50
    Cannot find name 'IRootScopeService'.

ERROR in [at-loader] node_modules\angular-ui-router\lib\templateFactory.d.ts:81:35
    Cannot find name 'IAugmentedJQuery'.

ERROR in [at-loader] node_modules\ui-router-ng1-to-ng2\ng1-to-ng2.ts:10:46
    Module '/node_modules/ui-router-ng2/lib/index"' has no exported member 'UIRouterRx'.

ERROR in [at-loader] node_modules\ui-router-ng1-to-ng2\ng1-to-ng2.ts:248:11
    Property 'viewConfigFactory' does not exist on type 'ViewService'.

ERROR in [at-loader] node_modules\ui-router-ng1-to-ng2\ng1-to-ng2.ts:252:11
    Property 'viewConfigFactory' does not exist on type 'ViewService'.

ERROR in [at-loader] node_modules\ui-router-ng1-to-ng2\ng1-to-ng2.ts:253:45
    Supplied parameters do not match any signature of call target.
Child html-webpack-plugin for "index.html":
        + 4 hidden modules

**Comment by christopherthielen** [comment]
I know this is very late to respond, but [2.0.0 is released](https://github.com/ui-router/angular-hybrid/releases/tag/2.0.0) and probably helps solve your issues.  You can see the [sample app](https://github.com/ui-router/sample-app-ng1-to-ng2) which is using webpack for reference.
