### ISSUE TITLE
Routes not working when used with unified Angular location service 

### ISSUE THREAD

**Issue by sajjidakr** [ui-router/angular-hybrid#320]
I have updated my project with angular 8 and used its unified location service after doing that following problems occurred 

1. Whenever i click a button using `ng-href="#/view1` the route don't work 
2. If i refresh a page while being on a specific route it does not detect route and re direct to the default route provided in `$urlRouterProvider.otherwise`
 
The problem happens only while using unified location service 

.factory('$location', downgradeInjectable($locationShim)

Reference:
https://angular.io/guide/upgrade#using-the-unified-angular-location-service

**Comment by christopherthielen** [comment]
I've verified this behavior by updating the [sample-app-angular-hybrid](https://github.com/ui-router/sample-app-angular-hybrid/compare/unified-location-service?expand=1) to use this unified location service.

What benefit will the unified location service provide to you @sajjidakr ?

**Comment by christopherthielen** [comment]
After further testing, the unified location service works when using pushState, but not when using `useHash: true`

**Comment by christopherthielen** [comment]
As a workaround, you can continue to use the AngularJS `$location` service.  You can upgrade it for use within your Angular components.

I reported this issue on the Angular repo.  You can follow it here: https://github.com/angular/angular/issues/34596
