### ISSUE TITLE
Add support for Angular 4?

### ISSUE THREAD

**Issue by brandon-a-hay** [ui-router/angular-hybrid#33]
Hi,

Is there any intention in upgrading the peer dependencies for this package to include Angular 4?

**Comment by matejkramny** [comment]
+1

There seems to be a release about this but can't use

**Comment by matejkramny** [comment]
How can we use this with angular 4?

**Comment by BenevidesLecontes** [comment]
I' waiting for this as well...

**Comment by mischkl** [comment]
It doesn't work with Angular 2.4 / AOT yet... Util that's fixed I guess Angular 4 won't work.

**Comment by christopherthielen** [comment]
We now support Angular 4 in JIT mode. See https://github.com/ui-router/angular-hybrid/releases/tag/2.0.0

**Comment by BenevidesLecontes** [comment]
@christopherthielen thanks for your amazing work, i'm grateful.
