### ISSUE TITLE
Version 8.0.0 needs old version of @uirouter/angular

### ISSUE THREAD

**Issue by odikusar** [ui-router/angular-hybrid#332]
The latest version of `ui-router/angular-hybrid` that supports Angular 8 depends on  `@uirouter/angular` version `3.0.0`, but this lib. not supports Angular 8.  Please change dependence `"@uirouter/angular": "3.0.0"` to `"@uirouter/angular": "3.0.0 || 4.0.0"`

**Comment by Pittan** [comment]
Hi, maybe this will help https://github.com/ui-router/angular-hybrid/pull/331

**Comment by eq-jxh188** [comment]
Please have someone with write access approve PR #331.

**Comment by wawyed** [comment]
Done and released in https://github.com/ui-router/angular-hybrid/blob/master/CHANGELOG.md
