### ISSUE TITLE
Router doesn't wait for APP_INITIALIZER

### ISSUE THREAD

**Issue by P3tronius** [ui-router/angular-hybrid#340]
Same issue from UIRouterModule: https://stackoverflow.com/questions/48567328/app-initializer-not-working-with-ui-router

Sadly, the workaround is not applicable here.
Any solution to get some code running before the initial route sync ?

**Comment by christopherthielen** [comment]
The workaround should be applicable to angular-hybrid.  Can you explain why it is not?

**Comment by christopherthielen** [comment]
In its initialization code, the sample hybrid app calls `deferIntercept()` then calls `listen()` when angular has bootstrapped.  This should happen _after any `APP_INITIALIZER` runs_.

https://github.com/ui-router/sample-app-angular-hybrid/blob/d95119c0d257a98e4ab2ef20504536d506822f57/app/main.ts#L38-L52
