### ISSUE TITLE
Bump to uirouter/angular 6.0.0?

### ISSUE THREAD

**Issue by stnor** [ui-router/angular-hybrid#373]
I'm trying to use
````
    resolvePolicy: { async: 'RXWAIT' },
````
in my hybrid app, but it is not a valid value according to StateDeclaration and ResolvePolicy.

Is the workaround to manually add 6.0.0 of uirouter/angular to package.json?

**Comment by wawyed** [comment]
The way you use  RXWAIT has changed. You need to provide the RXWAIT function exported in @uirouter/rx instead of a string.

```
import { RXWAIT } from '@uirouter/rx';

resolvePolicy: { async: RXWAIT }
```

**Comment by stnor** [comment]
jsdoc on ResolvePolicy is out of date

````
 * #### Example:
 * ```js
 * // Wait for an Observable to emit one item.
 * // Since `wait` is not specified, it uses the `wait`
 * // policy defined on the state, or the global default
 * // if no `wait` policy is defined on the state
 * var myResolvablePolicy = { async: "RXWAIT" }
 * ```
 */
export interface ResolvePolicy {
````

**Comment by wawyed** [comment]
Yes, my apologies. It was on my TODO list but haven't had time to update it.
