### ISSUE TITLE
Multiple instances of `@uirouter/core` due to `@uirouter/angular` and `@uirouter/angularjs`

### ISSUE THREAD

**Issue by gkalpak** [ui-router/angular-hybrid#392]
**Context:**

In the [angular/ngcc-validation][1] repo, we have an `@uirouter/angular-hybrid` project ([here][2]) to ensure that it remains compatible with the latest changes in [Ivy and ngcc][3]. The project is basically based on the instructions in [ui-router/angular-hybrid/README.md][4] and the [ui-router/sample-app-angular-hybrid][5] example.

Recently, after an automatic update of `@uirouter/core` from 6.0.1 to 6.0.2 (angular/ngcc-validation#720), we started getting a [failure on CI][6]. While looking into it, I found out the following:

- `@uirouter/angular-hybrid` has `@uirouter/angular` and `@uirouter/angularjs` as [peer dependencies][7].
- `@uirouter/angular` has `@uirouter/core@^6.0.1` as a [peer dependency][8].
- `@uirouter/angularjs` has `@uirouter/core@6.0.1` as a [direct dependency][9].

**The problem:**

Given that `@uirouter/angularjs@1.0.23` depends on `@uirouter/core@6.0.1` and one has to have `@uirouter/core` as a dependency on their project (due to it being a peer dependency of `@uirouter/angular`), the user can end up with one or two copies of `@uirouter/core` in their `node_modules/` (depending on how the package manager works).

For example, in our project, we had one copy of `@uirouter/core` when the project depended on `@uirouter/core@6.0.1` and the app worked correctly. As soon as we tried to update the project's `@uirouter/core` version to 6.0.2, we ended up with two copies of `@uirouter/core` (i.e. `@uirouter/angularjs` maintained its on instance of `@uirouter/core@6.0.1` in `node_modules/@uirouter/angularjs/node_modules/@uirouter/core/`).

As a result, the instance of `@uirouter/core` that was augmented by `@uirouter/angularjs` to [include service `$q`][10] was different than the `@uirouter/core` instance used by `@uirouter/angular-hybrid` (e.g. [here][11]). Consequently, `services.$q` is undefined in [Resolvable][12], causing a failure.

FWIW, I was able to fix the issue by forcing `@uirouter/angularjs` to use the latest `@uirouter/core` version via [yarn resolutions][13] (see angular/ngcc-validation#723).

**The question:**

If there are valid situations (such as hybrid apps) where people are expected to have `@uirouter/core` as a direct project dependency, isn't it a problem that `@uirouter/angularjs` also directly depends on `@uirouter/core`?

(It is also possible that we are doing something wrong (e.g. not having set up the example correctly), in which case any suggestions would be very much appreciated :smiley:)

##
For a reproduction, you can try to run the [uirouterangular-hybrid-ngcc][2] project by doing the following:

1. Check out angular/ngcc-validation@6bbffbbe7bc.
2. Run `yarn install`.
3. Run `yarn ng e2e --project uirouterangular-hybrid-ngcc`.
  (You can also replace `e2e` with `build` or `serve` if you want to manually test the app.)

BTW, this doesn't seem to be Ivy/ngcc specific. I can get the same issue with Ivy turned off (by setting `enabledIvy: false` in [tsconfig.json][14]).

[1]: https://github.com/angular/ngcc-validation
[2]: https://github.com/angular/ngcc-validation/tree/6bbffbbe7/projects/uirouterangular-hybrid-ngcc
[3]: https://v9.angular.io/guide/ivy
[4]: https://github.com/ui-router/angular-hybrid/blob/47ea2c641/README.md
[5]: https://github.com/ui-router/sample-app-angular-hybrid
[6]: https://circleci.com/gh/angular/ngcc-validation/2505#tests/containers/3
[7]: https://github.com/ui-router/angular-hybrid/blob/47ea2c641/package.json#L18-L19
[8]: https://github.com/ui-router/angular/blob/7140a74ad/package.json#L52
[9]: https://github.com/angular-ui/ui-router/blob/7065017b7/package.json#L75
[10]: https://github.com/angular-ui/ui-router/blob/f144e8b02/src/services.ts#L117
[11]: https://github.com/ui-router/angular-hybrid/blob/d53d134c5/src/angular-hybrid.ts#L258
[12]: https://github.com/ui-router/core/blob/23742e3e0/src/resolve/resolvable.ts#L85
[13]: https://yarnpkg.com/lang/en/docs/selective-version-resolutions
[14]: https://github.com/angular/ngcc-validation/blob/6bbffbbe7/tsconfig.json#L23

**Comment by oBusk** [comment]
@gkalpak Seems to be the same issue as https://github.com/angular-ui/ui-router/issues/3794

**Comment by gkalpak** [comment]
Or angular-ui/ui-router#3794 seems to be the same issue as this one 😛

**Comment by oBusk** [comment]
Important differance!

**Comment by christopherthielen** [comment]
We have historically used a direct dependency to an exact version of `@uirouter/core` in each release of `@uirouter/angularjs` so users could just depend on the one package and no changes to their package config (from the days of `angular-ui-router`).  When we released `@uirouter/angular-hybrid`, it depended on exact versions of `@uirouter/angular` and `@uirouter/angularjs`, both of which had direct deps on an exact version of `@uirouter/core`.   Up until late last year, I always made sure to bump deps in `@uirouter/angular`, `@uirouter/angularjs` and `@uirouter/angular-hybrid` each time we bumped `@uirouter/core` so there was always an exact combination of packages (blessed by the project) that would work together.  Now that `@uirouter/angular` and `angular-hybrid` use `peerDependencies` with caret ranges,  they will pull in the latest versions of these transitive dependencies.  I failed to bump `@uirouter/angularjs` (which still has a hard dependency) to the latest `@uirouter/core`, thus causing the problem.  

Now that I [released `@uirouter/angularjs@1.0.25`](https://github.com/angular-ui/ui-router/releases/tag/1.0.25) which depends on the latest core, there should be a a valid package combination.

In the future, I'll be migrating all the uirouter packages to `peerDependencies` and doing a major release.

@gkalpak let me know if releasing 1.0.25 has fixed the tests.

**Comment by christopherthielen** [comment]
> If there are valid situations (such as hybrid apps) where people are expected to have @uirouter/core as a direct project dependency, isn't it a problem that @uirouter/angularjs also directly depends on @uirouter/core?

Previously, no -- `@uirouter/core` was not intended be a direct dep.  However, this will change in the future and I will expect people to manage all the uirouter deps as top-level deps via `peerDependencies`.   I wrote a tool `npx check-peer-dependencies` to help with this (as the package version numbers differ wildly).

**Comment by gkalpak** [comment]
Thx for the explanation and the release, @christopherthielen.
And for creating angular/ngcc-validation#833, which confirms the new version fixes the problem for now :+1:
