### ISSUE TITLE
Lazy module: Error: Trying to get the AngularJS injector before it being set.

### ISSUE THREAD

**Issue by yadue** [ui-router/angular-hybrid#395]
Hey,

I try to make working lazy loading module in my app but constantly having issues with loading lazy module:

here's the demo:
https://stackblitz.com/edit/ui-router-angular-hybrid-zgagnq?file=app%2Fapp.module.ts

the last link, lazy module throws an error

Error: Trying to get the AngularJS injector before it being set.

I already tried different approaches how to solve that.

The only way I made it working it was when bootstrapped application twice like that:
```
platformBrowserDynamic().bootstrapModule(NgxAppModule).then(platformRef => {
    window['platformRef'] && window['platformRef'].destroy();
    window['platformRef'] = null;

    const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;

    upgrade.bootstrap(document.documentElement, [Ng1AppModule.name]);

    const urlService: UrlService = platformRef.injector.get(UIRouter).urlService;

    function startUIRouter() {
        urlService.listen();
        urlService.sync();
    }

    platformRef.injector.get<NgZone>(NgZone).run(startUIRouter);
});
```

``` 
ngDoBootstrap() {
        if (window['$injector']) {
            window['$injector'].get('$uiRouter').dispose();
            window['$injector'].get('$rootScope').$destroy();
        }
        this.upgrade.bootstrap(document.body, [Ng1AppModule.name]);
        window['$injector'] = (angular.element(document.body) as any).injector()
    }
```

but it doesn't look right and additionaly, none of the bindings in index.html are being updated from scope plus.

In the stackblitz you can see exactly whats the issue. Thanks in advance.

**Comment by christopherthielen** [comment]
Your stackblitz is using angular-hybrid v5.x. There was a fix in v6.x for this issue (see https://github.com/ui-router/angular-hybrid/issues/150#issuecomment-390455913)

I downloaded your stackblitz and updated it to react-hybrid 10.x.  After the following changes, your stackblitz works:

```
npm i
npm i @uirouter/angular-hybrid@^10 @uirouter/angular@^6 @uirouter/angularjs@^1 @uirouter/core@^6 @uirouter/rx@^0.6
npx ng update @angular/cli @angular/core
// edit app.module.ts
// Switch UIRouterUpgradeModule.forChild to UIRouterUpgradeModule.forRoot
// switch import('../lazy.module.ts') to import('../lazy.module')
npm start
```
