### ISSUE TITLE
git dependencies make installation failed behind proxy

### ISSUE THREAD

**Issue by gitawego** [ui-router/angular-hybrid#41]
our company is behind the proxy, when I try to install angular-hybrid, as the dependencies are git url with snapshot:
```text
"@uirouter/angular": "git://github.com/ui-router/angular#SNAPSHOT-20170612",
"@uirouter/angularjs": "git://github.com/angular-ui/ui-router#SNAPSHOT-20170612",
```

npm is trying to download directly from github which is disallowed in my company (using nexus proxy server. )

could you please make the dependencies npm only ?

**Comment by httpete** [comment]
+1 I have the same issue. Thank you.

**Comment by httpete** [comment]
Why are these using snapshots? Will we eventually get to be on the released versions of these two deps?

**Comment by mischkl** [comment]
IMHO these should be peer dependencies. Or, if it's really not possible to use the "vanilla" packages, they could be released with special tags on NPM and referenced that way.
