### ISSUE TITLE
export 'UIROUTER_ROOT_MODULE' was not found in '@uirouter/angular'

### ISSUE THREAD

**Issue by elielia** [ui-router/angular-hybrid#434]
Hi there,

I upgraded my Angular app to version 9 with Ivy. After that, my ng2 components won't load any more. I received this error #374  so as mentioned there upgraded to angular-hybrid 10.0.0 and added the required devDependencies.

But then I get the following error when launching the app:
`ERROR in ./node_modules/@uirouter/angular-hybrid/__ivy_ngcc__/fesm2015/uirouter-angular-hybrid.js 146:33-54
"export 'UIROUTER_MODULE_TOKEN' was not found in '@uirouter/angular'`

my package.json:

"dependencies": {
    "@angular/animations": "9.1.9",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.9",
    "@angular/compiler": "9.1.9",
    "@angular/core": "9.1.9",
    "@angular/forms": "9.1.9",
    "@angular/material": "9.2.4",
    "@angular/router": "9.1.9",
    "@angular/platform-browser": "9.1.9",
    "@angular/platform-browser-dynamic": "9.1.9",
    "@angular/upgrade": "9.1.9",
    "@uirouter/angular-hybrid": "10.0.0",
.....
  },
  "devDependencies": {
    "@uirouter/angular": "^6.0.2",
    "@uirouter/angularjs": "^1.0.26",
    "@uirouter/core": "^6.0.5",
    "@uirouter/rx": "^0.6.5"
......
  }

**Comment by elielia** [comment]
Updated:

Managed to solve it by changing the dependencies manually to:

{
"@uirouter/angular": "6.0.0",
    "@uirouter/core": "6.0.1",
    "@uirouter/rx": "0.6.0",
}

**Comment by ashispanigrahy** [comment]
Same issue here. downgrading the versions fixes the issue.
Requesting to have the dependencies path update in angular-hybrid.
 
Following now. Once I get the process I might chose to create PR later on.

**Comment by ProSpartan** [comment]
I just ran into the same problem today. From changing some stuff, I found that the problem came from @uirouter/angular 6.0.2. Bumping it down to 6.0.1 let me build without issue while retaining the other higher versions of uirouter dependencies.

**Comment by christopherthielen** [comment]
This should be fixed by `@uirouter/angular` in version 6.0.3

https://github.com/ui-router/angular/issues/810
https://github.com/ui-router/angular/releases/tag/6.0.3
