### ISSUE TITLE
How to augment all routes with additional resolve using decorator

### ISSUE THREAD

**Issue by yadue** [ui-router/angular-hybrid#463]
In angularjs there is a way to augment all routes with additional resolver like:
```js
state.resolve.security = function($q, profileService, $rootScope, appSecurity) {
    if (!profileService.authenticated) {
        return $q.reject('not-logged');
    }

    if (!profileService.hasRoles(roles)) {
         return $q.reject('insufficient-roles');
    }
};
```

How to do the same using angular-hybrid? What I mean it works just fine using angularjs+angular in hybrid mode but as we are slowly finishing our road to angular and we wanted to fully migrate. 

I tried using StageRegistry.decorator, but sounds like it's being run to early.
```js
        UIRouterUpgradeModule.forRoot({
            states: [
                ...states,
            ],
            config: (uiRouterInstance: UIRouter, injector: Injector, module: StatesModule) => {
                uiRouterInstance.stateRegistry.decorator('decorator',  (state: StateObject, parent?: BuilderFunction) => {

```
When defined like this it's firing up too late after decorating all routes so decorator itself is not being assigned to the state routes.

**Comment by christopherthielen** [comment]
Hi, late follow up but I wanted to mention a few things for posterity: 

1) I _think_ that AngularJS bootstraps before Angular, so AngularJS states are registered before Angular bootstraps, and before the decorator is registered.  I'd try moving the decorator to AngularJS config block until all states are migrated to Angular.

2) Once all states are in Angular, the config block in `forRoot` should be good.  The config block is run before the root module states are registered:

https://github.com/ui-router/angular/blob/master/src/uiRouterConfig.ts#L7-L12

3) The end result you want (security/auth) looks like something that would be much better suited for a *Transition Hook*, not a resolve.  
```ts
router.transitionService.onBefore({ from: '**', to: '**' }, (trans: Transition) => {
  const toState = trans.to();
  const requiredRoles = toState.data.requiredRoles; // or whatever -- you can add metadata to states
  if (!profileService.authenticated) {
    return $q.reject('not-logged');
  }

  if (!profileService.hasRoles(roles)) {
     return $q.reject('insufficient-roles');
  }
});
```
