### ISSUE TITLE
ui.router.upgrade' is not available!

### ISSUE THREAD

**Issue by ivan-slepchenko** [ui-router/angular-hybrid#465]
Error: [$injector:nomod] Module 'ui.router.upgrade' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I do everything like in documentation.

**Comment by christopherthielen** [comment]
This message most likely means the `@uirouter/angular-hybrid` code isn't actually being loaded

https://github.com/ui-router/angular-hybrid/blob/master/src/angular-hybrid.ts#L45-L51
