### ISSUE TITLE
Support for angular12

### ISSUE THREAD

**Issue by Macanta** [ui-router/angular-hybrid#530]
Is it possible to add support for angular 12? Facing some issues with a hybrid application that we recently updated to v12.

**Comment by mokipedia** [comment]
Using Angular 12 as hybrid app without issues. Only thing that is annoying are the npm warnings. If you have issues maybe open a bug ticket with more description?

**Comment by Vortilion** [comment]
@mokipedia Im currently trying to migrate from AngularJS 1.6 to Angular 12, using ui-router! Having so many issues, do you think you could help me out? Im having trouble getting it to work...

**Comment by mokipedia** [comment]
@Vortilion I sent you an email.

**Comment by stones** [comment]
An issue as well. It wasn't so much with angular 12  for us ( 12 worked, 12.1 failed) but it was webpack 5.

**Comment by christopherthielen** [comment]
I released a [new version](https://github.com/ui-router/angular-hybrid/releases/tag/13.0.0)  with ng12 and ng13 support
