### ISSUE TITLE
Not playing well with ngAnnotate

### ISSUE THREAD

**Issue by miked1090** [ui-router/angular-hybrid#55]
Hi, so I've been working on migrating an application to Angular and this week I converted an ng1 page that had some child routes. Originally, the state definition was using the template property, but I changed it to use component instead. This allowed child routes to be loaded in the component, and everything was working great until it was ran with the prod build. I started getting the following error when trying to navigate to that page.

`Error: $injector:unpr
Unknown Provider
Unknown provider: function AccountSettingsComponent() {
    }DirectiveProvider <-`

After messing with webpack a bit, I found the issue is caused when ngAnnotate is ran and when the component property is being used in the state definition.

Is this a known issue and if so is there a workaround? 

Thanks!

**Comment by mattlewis92** [comment]
I'm using this lib successfully with the [babel plugin](https://github.com/schmod/babel-plugin-angularjs-annotate) which is the successor to ngAnnotate, it might fix your problem 😄

**Comment by miked1090** [comment]
Got it working using ng-annotate-loader with ng-annotate-patched, rather than the plugin. 

Thanks for the tip @mattlewis92, was gonna try that if the loader didn't work out!

**Comment by mamacdon** [comment]
@miked1090 I'm getting the same error but I don't understand how ng-annotate factors in. Can you elaborate?

**Comment by k0nG** [comment]
Had the same issue with `ng-annotate-loader` and `ng-annotate-patched`. Thanks @mamacdon your fix worked.
