### ISSUE TITLE
It seems that the $stateprovider's resolve map is not respected

### ISSUE THREAD

**Issue by tbaehler** [ui-router/angular-hybrid#56]
I have 

.config(/*@ngInject*/($stateProvider) => {

        $stateProvider.state('login', {
            url: '/login',
            views: {
                main: {
                    ....
                },
                navigation: {
                   ...
                }
            },
            resolve : {
                langKeys: /*@ngInject*/ (languageService) => {
                    languageServie.loadAllLanguageKeys(),
                },
            }
        });

The languageServie get's called. The services loads the keys from the backend, but it does not wait. The view is already displayed. We use the resolve map a lot in our application. And need a way to get this working. Any ideas?
Thanks

**Comment by tbaehler** [comment]
It's not a problem of the resolve map, but the $stateChangeStart event does not get fired. So I can hopefully workaround this issue

**Comment by christopherthielen** [comment]
Make sure you `return` the promise in your resolve. 

`return languageServie.loadAllLanguageKeys(),`

Also state change events are deprecated. See the migrate to 1.0 guide for details.
