### ISSUE TITLE
Angular 14 compatibility

### ISSUE THREAD

**Issue by pschmiedel** [ui-router/angular-hybrid#572]
Angular 14 has been out for a while, are there any intentions to release a compatible version?

**Comment by devlinjunker** [comment]
I created a PR here: https://github.com/ui-router/angular-hybrid/pull/571 

not sure if anyone is around to pick it up and merge it

**Comment by pschmiedel** [comment]
Hi, thanks for the PR. Would be great if we get a new release, as we are still using UI-Router!

**Comment by MvHMontySCOUT** [comment]
Would be nice as we are also still using UI-Router! :) @christopherthielen

**Comment by IgorWolbers** [comment]
For now I have added this section to my `package.json` file which solves (hides) the issue.

```
  "overrides": {
    "@uirouter/angular": {
      "@angular/core": "$@angular/core",
      "@angular/common": "$@angular/common"
    },
    "@uirouter/angular-hybrid": {
      "@angular/core": "$@angular/core",
      "@angular/upgrade": "$@angular/upgrade"
    }
  }
```

**Comment by tadamczak** [comment]
I would appreciate merging PR aswell :) it's blocking us from upgrading to A14

**Comment by wawyed** [comment]
Version 14 relased which supports angular 14
