### ISSUE TITLE
Error bootstrapping AppModule Error: Cannot read properties of undefined (reading 'when')

### ISSUE THREAD

**Issue by jozzeed** [ui-router/angular-hybrid#573]
I tried implementing @ui-router/angular-hybrid in my angular 12 app and encountered the following error while bootstrapping: "Error bootstrapping AppModule
Error: Cannot read properties of undefined (reading 'when')". This seems to be coming from the $q and an issue importing the services.

At first I thought this was on my end but after some tuning I was able to reproduce the issue in the following [stackblitz.io](https://stackblitz.com/edit/ui-router-angular-hybrid-asae85?file=package.json)

From the other issues I have seen, it seems to be coming from having multiple dependencies to @uirouter/core. However, I am unsure how to solve the issue.  I tried with angular 13 and 14 (with the updated packages) but the result is the same

Any idea?

**Comment by wawyed** [comment]
Please have a look at https://github.com/ui-router/angular-hybrid/tree/master/example Just tested it and seems to be working fine. Reopen if you still have issues.
