### ISSUE TITLE
angular-hybrid.d.ts(1,23): error

### ISSUE THREAD

**Issue by AlexDaSoul** [ui-router/angular-hybrid#58]
Hi!

ERROR in node_modules/@uirouter/angular-hybrid/lib/angular-hybrid.d.ts(1,23): error TS2688: Cannot find type definition file for 'angular'.

windows 10 
Node v8.9.0
npm 5.5.1
AngularJs 1.6.6
angular-cli 1.5.0
Angular 5.0.0

**Comment by SamanthaAdrichem** [comment]
I have the same issue

```
[at-loader] ./node_modules/@uirouter/angular-hybrid/lib/angular-hybrid.d.ts:1:1
    TS2688: Cannot find type definition file for 'angular'.

[at-loader] ./node_modules/@uirouter/angular-hybrid/lib/angular-hybrid.d.ts:2:26
    TS7016: Could not find a declaration file for module 'angular'. node_modules/angular/index.js' implicitly has an 'any' type.
```

Any info yet?

**Comment by SamanthaAdrichem** [comment]
I resolved this error, by updating my typescript config to config below (though i wonder if i didn't just surpress the error)

```
{
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": [ "es6", "dom" ],
		"noImplicitAny": true,
		"suppressImplicitAnyIndexErrors": true,
		"declaration": false,
		"skipLibCheck": true
	}
}
```

**Comment by christopherthielen** [comment]
What version of `npm` or `yarn` do you use to install packages @SamanthaAdrichem @AlexDaSoul ?  You can fix this by adding the type defs `npm install @types/angular @types/jquery`.

We have those as a `devDependency` in angular-hybrid package.json, but maybe they need to be `dependency`?
