### ISSUE TITLE
Add support for v16 in @uirouter/angular-hybrid

### ISSUE THREAD

**Issue by vanhorickanthony** [ui-router/angular-hybrid#588]
As of right now, the latest supported Angular version is 15. We're in the process of upgrading from 15 to 16, and this is blocking us right now.

**Comment by olegomon** [comment]
Is there any plan to add Angular 16 support?

**Comment by wawyed** [comment]
I'm happy to review pull requests but I have limited capacity at the minute to do the upgrade.

**Comment by boxmein** [comment]
Waiting for https://github.com/ui-router/angular/issues/984
