### ISSUE TITLE
Hybrid router doesn't work

### ISSUE THREAD

**Issue by Xen3r0** [ui-router/angular-hybrid#59]
Hi,

I have un example projet using `ui-router` with `ngUpgrade`, but the state `jenkins.risques.evaluations.view` is not working : https://github.com/Xen3r0/angular-jenkins

Do you have an idea ?

Thanks

**Comment by christopherthielen** [comment]
This is probably because you've got dependencies to `@uirouter/angular` and `@uirouter/angularjs` [in your package.json](https://github.com/Xen3r0/angular-jenkins/blob/3dcac055bcd651ce586087fe69c86c2ee5740cee/package.json#L42-L44

**Comment by Xen3r0** [comment]
So, isn't work with latest angular version ? (5.0.5)

Any compatibility is schedule for Angular 5.0.5 ?

Thanks

**Comment by christopherthielen** [comment]
It should work with Angular 5 already.  The latest release depends on `"@uirouter/angular": "1.0.0-beta.9"` which supports Angular 5.

I removed the unnecessary packages from your repo in a PR. Then I deleted node_modules, ran `npm install` and `npm start` and it seems to work.

**Comment by Xen3r0** [comment]
It’s work ! Thanks :)
