### ISSUE TITLE
require statements not working in ng1-to-ng2.js

### ISSUE THREAD

**Issue by dlombardi** [ui-router/angular-hybrid#9]
lines 22-25 are throwing an error for my application.

```
var angular = require("angular");
var core_1 = require("@angular/core");
var angular_ui_router_1 = require("angular-ui-router");
var ui_router_ng2_1 = require("ui-router-ng2");
```

none of these are successful.

**Comment by christopherthielen** [comment]
Can you try again with new version 1.0.10

**Comment by christopherthielen** [comment]
Also, what is your setup? 
You need to have a module loader to use NG2.  Your module loader needs to be configured to load those modules so ng1-to-ng2 can find them.
